{
 "title": "[NAME]-app",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "namespace", "label": "Namespace", "query": "prometheus" },
   {
    "name": "job",
    "label": "job",
    "query": {
     "query": "label_values([NAME]_app_requests_total, job)"
    }
   },
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values([NAME]_app_requests_total, job)"
    }
   },
   {
    "name": "handler",
    "label": "Handler",
    "query": {
     "query": "label_values([NAME]_app_requests_total, handler)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "pod health",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (kube_pod_status_phase{phase=~\"Pending|Unknown|Failed\",namespace=\"$namespace\",pod=~\"snappdoctor-config.+\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "oomkill,crash looping",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (kube_pod_container_status_restarts_total{namespace=\"$namespace\",pod=~\"snappdoctor-config.+\"} - kube_pod_container_status_restarts_total{namespace=\"$namespace\",pod=~\"snappdoctor-config.+\"} offset 5m)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Requests",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(sum(cloud:routes:rps{route_name=~\"snappdoctor_[NAME]\"})) "
    }
   ]
  },
  {
   "title": "Network Bandwidth ",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "binbps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(irate(container_network_transmit_bytes_total{cluster=\"\", namespace=\"$namespace\", pod=~\"snappdoctor-[NAME]-.+\"}[$__range])) ",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "cpu usage",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(rate(container_cpu_usage_seconds_total{container!=\"\",namespace=~\"$namespace\",pod=~\"snappdoctor-[NAME].+\"}[$__range]))  / sum(container_spec_cpu_quota{container!=\"\"}/container_spec_cpu_period{container!=\"\",namespace=~\"$namespace\",pod=~\"snappdoctor-[NAME].+\"})  * 100)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "throttled second",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (rate(container_cpu_cfs_throttled_seconds_total{namespace=~\"$namespace\",pod=~\"snappdoctor-config.+\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "memory usage",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(100 * sum (container_memory_working_set_bytes{namespace=~\"$namespace\",pod=~\"snappdoctor-config.+\"}))/(sum (container_spec_memory_limit_bytes{namespace=~\"$namespace\",pod=~\"snappdoctor-config.+\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Traffic - Req/s by handler",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "sum(rate([NAME]_app_requests_total{handler=~\"$handler\"}[1m])) by (handler) != 0",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "{{ job }} - {{ method }} {{handler}}",
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Status Codes Trend",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate([NAME]_app_requests_total{handler=~\"$handler\"}[1m])) by (handler, status) != 0",
     "legendFormat": "{{handler}} - {{status}}"
    }
   ]
  },
  {
   "title": "Latency by handler",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by (handler, le) (rate([NAME]_app_request_duration_seconds_bucket{handler=~\"$handler\"}[5m])))",
     "legendFormat": "{{ job }} - {{ method }} {{ handler }} - p99"
    }
   ]
  },
  {
   "title": "Verify state",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "sum(rate([NAME]_verify_bank_request_total[5m])) by (gateway, state) != 0",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "{{gateway}} - {{state}}",
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Verify Outline",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "sum(rate([NAME]_verify_bank_request_total[5m])) by (state) != 0",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "{{gateway}} - {{state}}",
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Verify Procedures Latency",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "histogram_quantile(1, sum by (le) (rate([NAME]_verify_bank_request_duration_seconds_bucket[5m])))",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "Verify request to bank",
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "" },
     "expr": "histogram_quantile(1, sum by (le) (rate([NAME]_verify_db_financial_transaction_duration_seconds_bucket[5m])))",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "Financial DB TX",
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "" },
     "expr": "histogram_quantile(1, sum by (le) (rate([NAME]_verify_db_find_product_duration_seconds_bucket[5m])))",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "Find Order Product",
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "" },
     "expr": "histogram_quantile(1, sum by (le) (rate([NAME]_verify_db_find_transaction_duration_seconds_bucket[5m])))",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "Finding Invoice Transactions",
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "" },
     "expr": "histogram_quantile(1, sum by (le) (rate([NAME]_verify_db_find_product_duration_seconds_bucket[5m])))",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "Find Order Product",
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "" },
     "expr": "histogram_quantile(1, sum by (le) (rate([NAME]_verify_db_get_invoice_duration_seconds_bucket[5m])))",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "Finding Invoice",
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "" },
     "expr": "histogram_quantile(1, sum by (le) (rate([NAME]_verify_db_legacy_transaction_duration_seconds_bucket[5m])))",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "Teleyare TX",
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "" },
     "expr": "histogram_quantile(1, sum by (le) (rate([NAME]_verify_rabbit_produce_duration_seconds_bucket[5m])))",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "RabbitMQ publish",
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "" },
     "expr": "histogram_quantile(1, sum by (le) (rate([NAME]_settle_bank_request_duration_seconds_bucket[5m])))",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "Bank Settle",
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "" },
     "expr": "histogram_quantile(1, sum by (le) (rate([NAME]_reverse_bank_request_duration_seconds_bucket[5m])))",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "Bank Reverse",
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Bank Gateways Latency",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (le, gateway) (rate([NAME]_token_bank_request_duration_seconds_bucket{}[5m]))) != 0",
     "legendFormat": "Token - {{gateway}}"
    },
    {
     "expr": "histogram_quantile(0.99, sum by (le, gateway) (rate([NAME]_verify_bank_request_duration_seconds_bucket{}[5m]))) != 0",
     "legendFormat": "Verify - {{gateway}}"
    }
   ]
  },
  {
   "title": "Token Outline",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(gateway, product) (rate([NAME]_token_bank_request_total[5m])) != 0",
     "legendFormat": "{{gateway}} - {{product}}"
    }
   ]
  },
  {
   "title": "Token Outline",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(success) (rate([NAME]_token_bank_request_total[5m])) != 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Status Codes Trend",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "cloud:routes:rps{route_name=~\"snappdoctor_[NAME]\"}",
     "legendFormat": "{{http_status_code}}"
    }
   ]
  },
  {
   "title": "ResponseTime",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(.95, sum by (authority, namespace, le)(rate (envoy_logs_duration_bucket{authority=\"[NAME].snapp.doctor\"}[5m])))",
     "legendFormat": "95"
    },
    {
     "expr": "histogram_quantile(.75, sum by (authority, namespace, le)(rate (envoy_logs_duration_bucket{authority=\"[NAME].snapp.doctor\"}[5m])))",
     "legendFormat": "75"
    },
    {
     "expr": "histogram_quantile(.5, sum by (authority, namespace, le)(rate (envoy_logs_duration_bucket{authority=\"[NAME].snapp.doctor\"}[5m])))",
     "legendFormat": "50"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{cluster=\"\", pod=~\"snappdoctor-[NAME]-.+\"}) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "CPU Throttling",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(increase(container_cpu_cfs_throttled_periods_total{cluster=\"\", namespace=\"snappdoctor\", pod=~\"snappdoctor-[NAME]-.+\"}[5m])) by (pod)",
     "legendFormat": "{{http_status_code}}"
    }
   ]
  },
  {
   "title": "Memory  Usage",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 78 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "( sum by (pod) (container_memory_working_set_bytes{namespace=~\"$namespace\",pod=~\"snappdoctor-[NAME]-.+\"}))/(sum by (pod)(container_spec_memory_limit_bytes{namespace=~\"$namespace\",pod=~\"snappdoctor-[NAME]-.+\"}))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Network Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 90 },
   "fieldConfig": { "defaults": { "unit": "binbps" } },
   "targets": [
    {
     "expr": "sum(irate(container_network_transmit_bytes_total{cluster=\"\", namespace=\"$namspace\", pod=~\"snappdoctor-[NAME]-.+\"}[5m])) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Filesystem Usage",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 101 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "topk(25, sort_desc(sum(pod:container_fs_usage_bytes:sum{cluster=\"\", namespace=\"$namespace\", pod=~\"snappdoctor-[NAME].+\"}) BY (pod, namespace)))",
     "legendFormat": "{{pod}}"
    }
   ]
  }
 ]
}