consumes:
- application/json
info:
  title: Go App Template
  version: 0.0.1
produces:
- application/json
schemes:
- http
swagger: "2.0"

# object definitions
definitions:
  item:
    type: object
    properties:
      name:
        type: string

# paths

paths:
  /:
    get:
      responses:
        '200':
          description: ok