basePath: /
definitions:
  api.sampleIndexRequest:
    type: object
  api.sampleIndexResponse:
    type: object
host: snapp.doctor
info:
  contact:
    name: Doctor Backend
  title: Template API
  version: "1.0"
paths:
  /api/v1:
    get:
      consumes:
      - application/json
      parameters:
      - description: Index request
        in: body
        name: req
        required: true
        schema:
          $ref: '#/definitions/api.sampleIndexRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.sampleIndexResponse'
      summary: Sample Index
swagger: "2.0"
